### ISSUE TITLE
TO DO - First release to CRAN

### ISSUE THREAD

**Issue by stephaneguerrier** [SMAC-Group/avar#4]
- [x] Fix error with the grid in `plot.avar` function (@gaetanbakalli could you please address it?)
- [x] Add appveyor and travis ci (check usethis::add_travic and add_appveyor)
- [x] A pkgdown website (Github pages) and review it
- [x] Run checks (see http://r-pkgs.had.co.nz/check.html)
- [x] Make news and cran-comments
- [x] check if we forgot something: see http://r-pkgs.had.co.nz/release.html

**Comment by Nathanael-Claussen** [comment]
0 errors ✔ | 0 warnings ✔ | 1 note ✖

Packages suggested but not available for checking: ‘covr’ ‘testthat’. 

Covr will never be available for checking (Read: https://github.com/cran/covr#why-cant-covr-run-during-r-cmd-check)

Edit: Some people have suggested setting environment variable _R_CHECK_FORCE_SUGGESTS=false
